name: sql_sample_script
run-name: Setting up the Jen database
on: [push]
jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
    - name: Test Output
      run: echo "Here is a test"
  connect-remote:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show databases
      run: mysql -h ${{secrets.DBHOSTNAME}} --port 3306 -u${{secrets.DBUSER}} -p${{secrets.DBPASSWORD}} -e "SHOW DATABASES";
    - name: Run a sample SQL on remote
      run: mysql -h ${{secrets.DBHOSTNAME}} --port 3306 -u${{secrets.DBUSER}} -p${{secrets.DBPASSWORD}} -e "source  sql_sample/sql_sample_script.sql";